# Generated by Django 3.2.6 on 2021-12-01 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0002_alter_user_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_banned',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_moderator',
        ),
    ]
