# Generated by Django 3.1.2 on 2020-10-31 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redtube', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PornstarVideos',
            new_name='PornstarVideo',
        ),
    ]
