# Generated by Django 3.1.2 on 2020-10-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True, max_length=100, null=True)),
                ('preview_url', models.URLField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('customizable_price', models.BooleanField()),
                ('require_shipping', models.BooleanField()),
                ('custom_receipt', models.TextField(blank=True, null=True)),
                ('custom_permalink', models.URLField(blank=True, max_length=100, null=True)),
                ('subscription_duration', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.PositiveSmallIntegerField(help_text='in cents')),
                ('currency', models.CharField(max_length=10)),
                ('short_url', models.URLField(max_length=100)),
                ('formatted_price', models.CharField(max_length=10)),
                ('published', models.BooleanField()),
                ('shown_on_profile', models.BooleanField()),
                ('file_info', models.JSONField()),
                ('max_purchase_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('deleted', models.BooleanField()),
                ('custom_fields', models.JSONField()),
                ('custom_summary', models.TextField(blank=True, null=True)),
                ('variants', models.JSONField()),
                ('sales_count', models.PositiveSmallIntegerField(help_text='in cents')),
                ('sales_usd_cents', models.FloatField()),
            ],
        ),
    ]
