# Generated by Django 3.1.2 on 2020-10-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gumroad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100)),
                ('seller_id', models.CharField(max_length=24)),
                ('timestamp', models.CharField(max_length=50)),
                ('daystamp', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('product_name', models.CharField(max_length=100)),
                ('product_has_variants', models.BooleanField()),
                ('price', models.PositiveSmallIntegerField(help_text='in cents')),
                ('gumroad_fee', models.PositiveSmallIntegerField(help_text='in cents')),
                ('formatted_display_price', models.CharField(max_length=24)),
                ('formatted_total_price', models.CharField(max_length=24)),
                ('currency_symbol', models.CharField(max_length=4)),
                ('amount_refundable_in_currency', models.CharField(max_length=4)),
                ('product_id', models.CharField(max_length=24)),
                ('product_permalink', models.CharField(max_length=10)),
                ('refunded', models.BooleanField()),
                ('partially_refunded', models.BooleanField()),
                ('chargedback', models.BooleanField()),
                ('purchase_email', models.EmailField(max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=24, null=True)),
                ('paid', models.BooleanField()),
                ('has_variants', models.BooleanField()),
                ('variants_and_quantity', models.CharField(blank=True, max_length=50)),
                ('has_custom_fields', models.BooleanField()),
                ('custom_fields', models.JSONField()),
                ('order_id', models.PositiveIntegerField()),
                ('is_product_physical', models.BooleanField()),
                ('is_recurring_billing', models.BooleanField()),
                ('can_contact', models.BooleanField()),
                ('is_following', models.BooleanField()),
                ('is_additional_contribution', models.BooleanField()),
                ('discover_fee_charged', models.BooleanField()),
                ('is_gift_sender_purchase', models.BooleanField()),
                ('is_gift_receiver_purchase', models.BooleanField()),
                ('referrer', models.CharField(max_length=100)),
                ('card', models.JSONField()),
                ('product_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reviews_count', models.PositiveSmallIntegerField()),
                ('average_rating', models.FloatField()),
                ('quantity', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
