# Generated by Django 3.1.2 on 2020-10-30 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gumroad', '0002_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('product_id', models.CharField(max_length=24)),
                ('product_name', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=24)),
                ('user_email', models.EmailField(max_length=100)),
                ('purchase_ids', models.JSONField()),
                ('created_at', models.DateTimeField()),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('user_requested_cancellation_at', models.DateTimeField(blank=True, null=True)),
                ('charge_occurrence_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('recurrence', models.CharField(max_length=20)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='formatted_price',
            field=models.CharField(max_length=24),
        ),
    ]
