CREATE DATABASE :DB_NAME;
CREATE USER :DB_USER WITH PASSWORD :DB_USER_PASSWORD;
ALTER DATABASE :DB_NAME OWNER TO :DB_USER;
ALTER USER :DB_USER WITH superuser;
GRANT CONNECT ON DATABASE :DB_NAME TO :DB_USER;